name: lint

on: push

jobs:
  steps:
  - run: npm install black && black .

# stages:
# # Build and push docker image to Azure container registry.
# - stage: Install Black
#   displayName: 'Instal Black'
#   jobs:
#     steps:
#     - run: npm install
